### ISSUE TITLE
Can't Install plugin 

### ISSUE THREAD

**Issue by tiger-githubb** [areeburrub/tailwindcss-flow-launcher-plugin#4]
![image](https://github.com/areeburrub/tailwindcss-flow-launcher-plugin/assets/98205891/e9926822-2762-4c71-993d-d8b7ee3416d5)
Need Help Please . What is pm

**Comment by areeburrub** [comment]
You don't have to run this command in the CMD terminal instead run the command in the FlowLauncher it self.

press "ALT + SPACE" this will open the launcher then write `pm install tailwindcss`

It will surely work 👍

**Comment by tiger-githubb** [comment]
> You don't have to run this command in the CMD terminal instead run the command in the FlowLauncher it self.
> 
> press "ALT + SPACE" this will open the launcher then write `pm install tailwindcss`
> 
> It will surely work 👍

It work Thanks . 
if you want to make one more feature, I suggest that when you do a search on the docs and the page is still open that the next reopens on the same page. And the second suggestion is to add another property that will allow you to copy the property when you find it directly in the flow lancher. 

In any case, thanks for this plugin, it works like a charm. 😊
